[global]
address = "0.0.0.0"
port = 7609

[default]
ip_header = "X-Real-IP"
car_vin = "LRW3AAAAAAA000000"
tessie_token = "get token from Tessie App"
charger_location = "43.363056,-8.838417"
max_amps = 10.2
max_amps_car = 9

[default.databases.sqlite_logs]
url = "./sqlite.db"
